/* tslint:disable */
/* eslint-disable */
/**
 * Vikunja API
 * # Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we\'re using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja\'s documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v0.23.0-879-f2ac9c2cca
 * Contact: hello@vikunja.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsReminderRelation } from './ModelsReminderRelation';
import {
    ModelsReminderRelationFromJSON,
    ModelsReminderRelationFromJSONTyped,
    ModelsReminderRelationToJSON,
} from './ModelsReminderRelation';

/**
 * 
 * @export
 * @interface ModelsTaskReminder
 */
export interface ModelsTaskReminder {
    /**
     * A period in seconds relative to another date argument. Negative values mean the reminder triggers before the date. Default: 0, tiggers when RelativeTo is due.
     * @type {number}
     * @memberof ModelsTaskReminder
     */
    relativePeriod?: number;
    /**
     * The name of the date field to which the relative period refers to.
     * @type {ModelsReminderRelation}
     * @memberof ModelsTaskReminder
     */
    relativeTo?: ModelsReminderRelation;
    /**
     * The absolute time when the user wants to be reminded of the task.
     * @type {string}
     * @memberof ModelsTaskReminder
     */
    reminder?: string;
}

/**
 * Check if a given object implements the ModelsTaskReminder interface.
 */
export function instanceOfModelsTaskReminder(value: object): value is ModelsTaskReminder {
    return true;
}

export function ModelsTaskReminderFromJSON(json: any): ModelsTaskReminder {
    return ModelsTaskReminderFromJSONTyped(json, false);
}

export function ModelsTaskReminderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsTaskReminder {
    if (json == null) {
        return json;
    }
    return {
        
        'relativePeriod': json['relative_period'] == null ? undefined : json['relative_period'],
        'relativeTo': json['relative_to'] == null ? undefined : ModelsReminderRelationFromJSON(json['relative_to']),
        'reminder': json['reminder'] == null ? undefined : json['reminder'],
    };
}

export function ModelsTaskReminderToJSON(value?: ModelsTaskReminder | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'relative_period': value['relativePeriod'],
        'relative_to': ModelsReminderRelationToJSON(value['relativeTo']),
        'reminder': value['reminder'],
    };
}

