/* tslint:disable */
/* eslint-disable */
/**
 * Vikunja API
 * # Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we\'re using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja\'s documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v0.23.0-832-2d358a57cc
 * Contact: hello@vikunja.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsDatabaseNotifications
 */
export interface ModelsDatabaseNotifications {
    /**
     * A timestamp when this notification was created. You cannot change this value.
     * @type {string}
     * @memberof ModelsDatabaseNotifications
     */
    created?: string;
    /**
     * The unique, numeric id of this notification.
     * @type {number}
     * @memberof ModelsDatabaseNotifications
     */
    id?: number;
    /**
     * The name of the notification
     * @type {string}
     * @memberof ModelsDatabaseNotifications
     */
    name?: string;
    /**
     * The actual content of the notification.
     * @type {object}
     * @memberof ModelsDatabaseNotifications
     */
    notification?: object;
    /**
     * Whether or not to mark this notification as read or unread.
     * True is read, false is unread.
     * @type {boolean}
     * @memberof ModelsDatabaseNotifications
     */
    read?: boolean;
    /**
     * When this notification is marked as read, this will be updated with the current timestamp.
     * @type {string}
     * @memberof ModelsDatabaseNotifications
     */
    readAt?: string;
}

/**
 * Check if a given object implements the ModelsDatabaseNotifications interface.
 */
export function instanceOfModelsDatabaseNotifications(value: object): value is ModelsDatabaseNotifications {
    return true;
}

export function ModelsDatabaseNotificationsFromJSON(json: any): ModelsDatabaseNotifications {
    return ModelsDatabaseNotificationsFromJSONTyped(json, false);
}

export function ModelsDatabaseNotificationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsDatabaseNotifications {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'notification': json['notification'] == null ? undefined : json['notification'],
        'read': json['read'] == null ? undefined : json['read'],
        'readAt': json['read_at'] == null ? undefined : json['read_at'],
    };
}

export function ModelsDatabaseNotificationsToJSON(value?: ModelsDatabaseNotifications | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created': value['created'],
        'id': value['id'],
        'name': value['name'],
        'notification': value['notification'],
        'read': value['read'],
        'read_at': value['readAt'],
    };
}

