/* tslint:disable */
/* eslint-disable */
/**
 * Vikunja API
 * # Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we\'re using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja\'s documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v0.23.0-832-2d358a57cc
 * Contact: hello@vikunja.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserUser } from './UserUser';
import {
    UserUserFromJSON,
    UserUserFromJSONTyped,
    UserUserToJSON,
} from './UserUser';

/**
 * 
 * @export
 * @interface ModelsLabel
 */
export interface ModelsLabel {
    /**
     * A timestamp when this label was created. You cannot change this value.
     * @type {string}
     * @memberof ModelsLabel
     */
    created?: string;
    /**
     * The user who created this label
     * @type {UserUser}
     * @memberof ModelsLabel
     */
    createdBy?: UserUser;
    /**
     * The label description.
     * @type {string}
     * @memberof ModelsLabel
     */
    description?: string;
    /**
     * The color this label has in hex format.
     * @type {string}
     * @memberof ModelsLabel
     */
    hexColor?: string;
    /**
     * The unique, numeric id of this label.
     * @type {number}
     * @memberof ModelsLabel
     */
    id?: number;
    /**
     * The title of the lable. You'll see this one on tasks associated with it.
     * @type {string}
     * @memberof ModelsLabel
     */
    title?: string;
    /**
     * A timestamp when this label was last updated. You cannot change this value.
     * @type {string}
     * @memberof ModelsLabel
     */
    updated?: string;
}

/**
 * Check if a given object implements the ModelsLabel interface.
 */
export function instanceOfModelsLabel(value: object): value is ModelsLabel {
    return true;
}

export function ModelsLabelFromJSON(json: any): ModelsLabel {
    return ModelsLabelFromJSONTyped(json, false);
}

export function ModelsLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'createdBy': json['created_by'] == null ? undefined : UserUserFromJSON(json['created_by']),
        'description': json['description'] == null ? undefined : json['description'],
        'hexColor': json['hex_color'] == null ? undefined : json['hex_color'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'updated': json['updated'] == null ? undefined : json['updated'],
    };
}

export function ModelsLabelToJSON(value?: ModelsLabel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created': value['created'],
        'created_by': UserUserToJSON(value['createdBy']),
        'description': value['description'],
        'hex_color': value['hexColor'],
        'id': value['id'],
        'title': value['title'],
        'updated': value['updated'],
    };
}

