/* tslint:disable */
/* eslint-disable */
/**
 * Vikunja API
 * # Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we\'re using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja\'s documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: v0.23.0-832-2d358a57cc
 * Contact: hello@vikunja.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1OpenIDAuthInfo } from './V1OpenIDAuthInfo';
import {
    V1OpenIDAuthInfoFromJSON,
    V1OpenIDAuthInfoFromJSONTyped,
    V1OpenIDAuthInfoToJSON,
} from './V1OpenIDAuthInfo';
import type { V1LocalAuthInfo } from './V1LocalAuthInfo';
import {
    V1LocalAuthInfoFromJSON,
    V1LocalAuthInfoFromJSONTyped,
    V1LocalAuthInfoToJSON,
} from './V1LocalAuthInfo';

/**
 * 
 * @export
 * @interface V1AuthInfo
 */
export interface V1AuthInfo {
    /**
     * 
     * @type {V1LocalAuthInfo}
     * @memberof V1AuthInfo
     */
    local?: V1LocalAuthInfo;
    /**
     * 
     * @type {V1OpenIDAuthInfo}
     * @memberof V1AuthInfo
     */
    openidConnect?: V1OpenIDAuthInfo;
}

/**
 * Check if a given object implements the V1AuthInfo interface.
 */
export function instanceOfV1AuthInfo(value: object): value is V1AuthInfo {
    return true;
}

export function V1AuthInfoFromJSON(json: any): V1AuthInfo {
    return V1AuthInfoFromJSONTyped(json, false);
}

export function V1AuthInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AuthInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'local': json['local'] == null ? undefined : V1LocalAuthInfoFromJSON(json['local']),
        'openidConnect': json['openid_connect'] == null ? undefined : V1OpenIDAuthInfoFromJSON(json['openid_connect']),
    };
}

export function V1AuthInfoToJSON(value?: V1AuthInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'local': V1LocalAuthInfoToJSON(value['local']),
        'openid_connect': V1OpenIDAuthInfoToJSON(value['openidConnect']),
    };
}

